### ISSUE TITLE
ขอ ICON ทั้งหมดที่ใช้งานใน Project

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#25]
รบกวนส่ง ICON ทั้งหมดที่ใช้งานใน Project ด้วยนะคะ

ขอบคุณคะ

**Comment by wannarukb** [comment]
[mobile icon.zip](https://github.com/wannarukb/RDPB-System/files/1260406/mobile.icon.zip)
Icon ในส่วนของ Mobile ค่ะ แยกเป็น 
- img => กรณีต้องการใช้แบบรูปภาพค่ะ
- svg

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ  ครบถ้วน

**Comment by Srikridsadaporn** [comment]
รบกวนส่ง ICON ศูนย์เรียนรู้เศรษฐกิจพอเพียง และศูนย์ศึกษาฯ ที่ได้ออกแบบใหม่ด้วยนะคะ 
ปล. ส่วนนี้ยังไม่เคยส่งเป็น Icon แยก แต่เคยส่งเป็นไฟล์รวมให้พี่เลือก
ขอบคุณคะ  รบกวนขอด่วนมาก
@wannarukb

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ ขอโทษค่ะ ตอนแรกเข้าใจว่าส่งไปแล้ว >_< จำผิด
[icon v2.zip](https://github.com/wannarukb/RDPB-System/files/1296486/icon.v2.zip)

**Comment by Srikridsadaporn** [comment]
@wannarukb 
น้องเล็กคะ  รบกวนขอใหม่อีกครั้งนะคะ เพราะ Icon ของศูนย์ศึกษาฯ ไม่ใช่แบบที่ลูกค้าเลือกไว้
ดูตามภาพด้านล่างได้เลยคะ  ขอโทษที่ครั้งแรกไม่ใส่ภาพมาให้  พี่ก็ลืมไปว่ารายละเอียดใกล้เคียงกันมากถ้าส่งมาแค่ภาพเดียวอาจพลาดได้

ขอบคุณมากนะคะ

![image](https://user-images.githubusercontent.com/31124544/30355509-1683c174-985e-11e7-9bf5-043ec11a42ad.png)

**Comment by wannarukb** [comment]
[icon v2.zip](https://github.com/wannarukb/RDPB-System/files/1301716/icon.v2.zip)
