### ISSUE TITLE
Back office : ปรับปรุงหน้าจอ เพิ่มข้อมูลศูนย์เรียนรู้เศรษฐกิจพอเพียง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [wannarukb/RDPB-System#26]
ขอให้ปรับแก้ตามหน้าจอด้านล่าง
![2](https://user-images.githubusercontent.com/30930235/29802444-647e76fa-8c9f-11e7-948e-447e9a0887df.png)

**Comment by RDPB2-Kuer** [comment]
ช่วยแก้หน้าจอของศูนย์เรียนรู้อันอื่น ตรงที่มีข้อมูลเหมือนกันด้วยนะค่ะ

**Comment by wannarukb** [comment]
ปรับเรียบร้อยแล้วค่ะ 
<img width="1018" alt="screen shot 2017-08-30 at 23 28 06" src="https://user-images.githubusercontent.com/23309321/29883551-e808c52a-8dda-11e7-8820-0cefff699c31.png">

**Comment by Srikridsadaporn** [comment]
ช่วยปรับตามภาพด้านล่างด้วยนะคะ...ขอบคุณค่ะ

![image](https://user-images.githubusercontent.com/31124544/29905426-e09116c2-8e38-11e7-83e3-0701083f01cb.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1019" alt="screen shot 2017-08-31 at 20 01 47" src="https://user-images.githubusercontent.com/23309321/29924477-3db447b8-8e87-11e7-91e4-d5a01d4b74d6.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
