### ISSUE TITLE
 Back office : ปรับปรุงหน้าจอศูนย์เรียนรู้เศรษฐกิจพอเพียง - รูปภาพ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [wannarukb/RDPB-System#27]
ขอปรับแก้ ดังภาพล่างนี้
![2 1](https://user-images.githubusercontent.com/30930235/29803320-17755b52-8ca5-11e7-999a-2f3bfffe65cb.png)

**Comment by RDPB2-Kuer** [comment]
ที่เอกสารประกอบ ก็แก้เช่นเดียวกันค่ะ

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
รูปภาพ
<img width="1013" alt="screen shot 2017-08-29 at 20 54 33" src="https://user-images.githubusercontent.com/23309321/29824667-56482416-8cfc-11e7-9cd8-e237544a6729.png">

เอกสารประกอบ
<img width="1019" alt="screen shot 2017-08-29 at 20 54 38" src="https://user-images.githubusercontent.com/23309321/29824676-5dea7070-8cfc-11e7-944a-4a5c69ecb050.png">
