### ISSUE TITLE
Back Office : ปรับแก้หน้าจอหน้าค้นหาศูนย์เรียนรู้หน่วยงานต่างๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#29]
ปรับแก้หน้าจอหน้าค้นหาศูนย์เรียนรู้หน่วยงานต่างๆ ตามภาพค่ะ

![image](https://user-images.githubusercontent.com/31124544/29810603-a6b37766-8cca-11e7-8859-1a8ad0086e24.png)

**Comment by wannarukb** [comment]
แบบนี้นะคะ
<img width="1264" alt="screen shot 2017-08-29 at 20 52 47" src="https://user-images.githubusercontent.com/23309321/29824547-0f098856-8cfc-11e7-9d62-174702fe11b5.png">

**Comment by Srikridsadaporn** [comment]
น้องคะ  พี่จะปรับแก้ตามไฟล์แนบนะคะ

2017-08-29 20:53 GMT+07:00 wannarukb <notifications@github.com>:

**Comment by Srikridsadaporn** [comment]
เนื่องจากส่วนนี้พี่บอกพลาดหลายตำแหน่ง   เลยลองปรับเองดูตามภาพด้านล่าง
ถ้าคิดว่าดูไม่สวยรบกวนปรับใหม่ด้วยนะคะ


![default](https://user-images.githubusercontent.com/31124544/29855788-c6f80da8-8d78-11e7-9ec4-54a3b1d26224.png)

**Comment by RDPB2-Kuer** [comment]
ต้องขอให้ปรับแก้ตามที่พี่หญิงทำใน slide ล่าสุดด้วยนะค่ะ

**Comment by wannarukb** [comment]
ปรับเรียบร้อยค่ะ
<img width="1262" alt="screen shot 2017-08-30 at 22 29 54" src="https://user-images.githubusercontent.com/23309321/29880755-cca3ac30-8dd2-11e7-9bf7-aa98a221b2bc.png">

**Comment by Srikridsadaporn** [comment]
รบกวนปรับอีกครั้งตามภาพด้านล่างนะคะ....ถ้าหากไม่เคลียร์ถามมาได้เลยนะคะ


![image](https://user-images.githubusercontent.com/31124544/29904157-ad888fc8-8e31-11e7-828a-8b64aaca189b.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1020" alt="screen shot 2017-08-31 at 19 53 49" src="https://user-images.githubusercontent.com/23309321/29924147-26263828-8e86-11e7-8c48-0258f48817ee.png">
