### ISSUE TITLE
เพิ่ม ศูนย์ศึกษาการพัฒนา เข้ามาเป็นเมนูที่สี่

### ISSUE THREAD

**Issue by cmmadnat** [wannarukb/RDPB-System#3]
คล้ายกับศูนย์เรียนรู้ประเภทอื่น มีตัวอย่างข้อมูลดังต่อไปนี้
![image_42f5164](https://user-images.githubusercontent.com/37333/29215691-2d176310-7ed6-11e7-80f1-d5ecadc85ec8.jpg)

**Comment by Srikridsadaporn** [comment]
กปร.ยืนยันแล้ว ขอให้ปรับแก้ตามรายละเอียดได้เลยค่ะ
