### ISSUE TITLE
ฺBack Office : ปรับแก้การค้นหาศูนย์เรียนรู้เศรษฐกิจพอเพียง

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#30]
ปรับแก้การค้นหาศูนย์เรียนรู้เศรษฐกิจพอเพียงตามภาพด้านล่างด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/29810684-f07bdbc2-8cca-11e7-9f2d-b25c58efd4e2.png)

**Comment by wannarukb** [comment]
แก้เป็นแบบนี้นะคะ
<img width="1267" alt="screen shot 2017-08-29 at 20 43 00" src="https://user-images.githubusercontent.com/23309321/29824063-ad751bb0-8cfa-11e7-871a-888793fbfcd7.png">

**Comment by Srikridsadaporn** [comment]
รบกวนปรับอีกครั้งนะคะ ขอโทษที่เขียนไม่เคลียร์
ส่วนของชื่อคน/ชุมชน จะค้นหาจากการค้นหาหลักเลยคะ  ดังนั้นจึงไม่มี  ตามภาพด้านล่างนะคะ

![image](https://user-images.githubusercontent.com/31124544/29851734-0aef5b4c-8d60-11e7-94f5-b08e951bc697.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1265" alt="screen shot 2017-08-30 at 22 33 56" src="https://user-images.githubusercontent.com/23309321/29880937-5dca95ca-8dd3-11e7-82ee-b9157aaa3666.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ...ปิด
