### ISSUE TITLE
Back Office : ปรับแก้การค้นหาศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#31]
ปรับแก้การค้นหาศูนย์เรียนรู้ตามแนวพระราชดำริ ตามภาพด้านล่างด้วยค่ะ
![image](https://user-images.githubusercontent.com/31124544/29810859-afaef470-8ccb-11e7-8ba7-afb72ba357c2.png)

**Comment by wannarukb** [comment]
แบบนี้นะคะ ^^ 
<img width="1266" alt="screen shot 2017-08-29 at 20 46 35" src="https://user-images.githubusercontent.com/23309321/29824254-34208988-8cfb-11e7-9c62-1836abc90802.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ..
