### ISSUE TITLE
Mobile : ออกแบบหน้าจอให้# ผู้ใช้เลือก  ** ระหว่างโครงการฯ และ ศูนย์เรียนรู้** 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#32]
รบกวนออกแบบหน้าจอให้**# ผู้ใช้เลือกระหว่างโครงการฯ และ ศูนย์เรียนรู้** หลังจากที่ผู้ใช้เปิด Application แล้วด้วยนะคะ

**Comment by wannarukb** [comment]
<img width="300" alt="screen shot 2017-08-30 at 14 10 29" src="https://user-images.githubusercontent.com/23309321/29859793-f728ad9c-8d8d-11e7-9e05-9cfd76b3f2b1.png">
