### ISSUE TITLE
Back Office : ขอตัวอย่างหน้า Dashbord

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#33]
ขอตัวอย่างหน้า Dashbord ที่ปรับแก้ให้สอดคล้องกับงานข้อมูลศูนย์เรียนรู้ด้วยนะคะ
ภาพด้านล่างคือแบบที่ กปร. เลือกใช้ค่ะ

![image](https://user-images.githubusercontent.com/31124544/29855599-269733ee-8d77-11e7-874c-2f9bd6b241e9.png)

**Comment by RDPB2-Kuer** [comment]
ขอชี้แจงเพิ่มเติมความต้องการ ดังนี้ค่ะ คือ พอดีเราเห็นตัวอย่างของ Dashboard ดังภาพด้านบน เลยอยากจะได้ตัวอย่างเหล่านี้ ไปนำเสนอให้ กปร. เห็นภาพและสามารพยืนยันความต้องการในส่วน Dashboard ได้นะค่ะ 
หากน้องจะส่งให้เป็นภาพของแต่ละกราฟก็จะดีมากค่ะ

**Comment by wannarukb** [comment]
เพิ่มแล้วค่ะ
<img width="1266" alt="screen shot 2017-09-01 at 01 25 37" src="https://user-images.githubusercontent.com/23309321/29938931-7f8bbd88-8eb4-11e7-9a7e-ed3fb342c3b1.png">

**Comment by Srikridsadaporn** [comment]
ขอชี้แจงเพิ่มเติมนะคะ  Dashbord นี้เป็นส่วนการแสดงผลของข้อมูลในโครงการ ซึ่งประกอบด้วย
1.ศูนย์เรียนรู้เศรษฐกิจพอเพียง
2.ศูนย์เรียนรู้ตามแนวพระราชดำริฯ
3.ศูนย์เรียนรู้หน่วยงานต่างๆ
4.ศูนย์การศึกษาการพัฒนา
ดังนั้นต้องปรับแก้ส่วน Dashbord ให้แสดงข้อมูลใน 4 ส่วนนี้นะคะ
ส่วนการอนุมัติข้อมูลทั้งส่วนมีเดีย  ค่าพิกัดและการอนุมัติได้รับการยกเลิกไปแล้ว...ดังนั้นไม่าต้องมีการแสดงข้อมูลส่วนนี้
...ขอโทษด้วยคะที่ข้อมูลไม่ชัดเจน  ดังนั้นรบกวนปรับอีกครั้ง...ขอบคุณคะ

**Comment by wannarukb** [comment]
ปรับให้แล้วนะคะ แต่ยังไม่ค่อยแน่ใจว่า เป็น Dashboard ตัวเลขสรุปด้านบน ที่ต้องการไหมคะ
อันนี้ลองปรับตามความเข้าใจค่ะ
<img width="1264" alt="screen shot 2017-09-04 at 01 36 01" src="https://user-images.githubusercontent.com/23309321/30005661-82c4fa28-9111-11e7-9a12-2f732b1aa66b.png">

**Comment by Srikridsadaporn** [comment]
รบกวนปรับตามภาพด้านล่างด้วยนะคะ...ขอบคุณคะ

![image](https://user-images.githubusercontent.com/31124544/30017055-d37f1bae-9181-11e7-8093-e707603fcc77.png)

**Comment by wannarukb** [comment]
ปรับเรียบร้อยแล้วค่ะ
<img width="1280" alt="screen shot 2017-09-08 at 01 17 49" src="https://user-images.githubusercontent.com/23309321/30178564-923a9b32-9433-11e7-883d-1dbca11969f8.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
