### ISSUE TITLE
Back Office : ปรับ Panel Menu ด้วยนะคะ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#34]
ปรับ Panel Menu ตามภาพ

![image](https://user-images.githubusercontent.com/31124544/29865154-056b04ca-8d9f-11e7-8359-831231e34e21.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
ตรงนี้อยากรบกวนขอคำอธิบายรายงานการใช้งานระบบ นิดหน่อยได้ไหมคะ
เป็นการรายงานว่า User ท่านใด Login เข้ามาบ้าง หรือ รายงานในด้านไหนคะ 
<img width="312" alt="screen shot 2017-08-30 at 22 23 04" src="https://user-images.githubusercontent.com/23309321/29880391-d694b2da-8dd1-11e7-99fb-e2cb993bf21e.png">

**Comment by RDPB2-Kuer** [comment]
เป็นการรายงานว่า User ท่านใด Login เข้ามาใช้งานระบบบ้าง วันไหน เวลาไหนค่ะ

**Comment by Srikridsadaporn** [comment]
อย่าลืม...แก้ font กับ logo ***ทุกหน้า***ด้วยนะค่ะ
