### ISSUE TITLE
ขอคำปรึกษาการแจ้งปัญหา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [wannarukb/RDPB-System#35]
จะขอเพิ่ม Label ได้อย่างไร คือ อยากจะเพิ่ม Lab​​el ดังนี้ "Fix" เพื่อให้น้องแจ้งพี่ว่า ปัญหาไหนที่แก้ไขแล้ว และรอให้พี่ปิดนะค่ะ หรือถ้าเพิ่มไม่ได้ เราจะใช้ Label ไหนที่ให้พี่เข้าใจว่าน้องแก้แล้ว รอพี่ปิด

**Comment by wannarukb** [comment]
เล็กเพิ่มแล้วนะคะ ตอนแรกหานานมากเลย ..​ ขอโทษนะคะ ตอนนั้นๆ งงมากเลย ปิดมั่วไปนิดหน่อย
ถ้า  issue ตัวไหนที่แก้แล้วผิด สามารถเลือกเป็น Fail ไว้ได้เลยนะคะ

**Comment by RDPB2-Kuer** [comment]
ไม่ทราบว่าพี่จะเพิ่ม label ได้อย่างไรค่ะ

**Comment by Srikridsadaporn** [comment]
น้องเล็กคะ ส่วน  label  ที่จะให้เลือกเป็น Fail ในกรณีที่ปรับแล้วยังไม่ตรงกับความต้องการ...พี่พยายามหาวิธีการทำแล้วแต่ไม่ได้  รบกวนแนะนำหน่อยคะ  น้องเล็กจะได้ทำงานสะดวกและเร็วขึ้นไม่ต้องมาคอยเช็คว่าพี่เขียนอะไรใน Issue ไหนเพิ่มบ้าง...ขอบคุณล่วงหน้าค่ะ @wannarukb

**Comment by RDPB2-Kuer** [comment]
น้องเล็กค่ะ .... รบกวนบอกวิธีเปลี่ยน label ให้พี่ทีค่ะ

**Comment by wannarukb** [comment]
เล็กลอง invite เป็น collaborator ของ project ดู อาจจะเปลี่ยนได้นะคะ

**Comment by RDPB2-Kuer** [comment]
ยังไม่ได้เลยค่ะ ปกติถ้าเปลี่ยนได้จะทำตรงไหนค่ะ

**Comment by wannarukb** [comment]
กดรับ invitations ก่อนนะฮะ
https://github.com/wannarukb/RDPB-System/invitations

พอรับแล้วจะได้กด Label ได้ฮะะ

![group](https://user-images.githubusercontent.com/23309321/30193067-576ab946-9475-11e7-9c65-67dc074926ae.png)

**Comment by Srikridsadaporn** [comment]
ทำได้แล้วค่ะ....ขอบคุณนะคะ

**Comment by RDPB2-Kuer** [comment]
ทำได้แล้วค่ะ
