### ISSUE TITLE
เพิ่มขนาดของตัวอักษรในตาราง

### ISSUE THREAD

**Issue by cmmadnat** [wannarukb/RDPB-System#36]
ของเดิมเป็น 18px ค่อนข้างเล็กไป ขอให้เป็น 24
![image_61c8935](https://user-images.githubusercontent.com/37333/29905655-2cf5e4f6-8e3a-11e7-9183-bd9bd6bb543c.jpg)

ลองพิจารณาว่าส่วนไหนบ้างที่มันดูเล็กไป เพราะว่าค่อนข้างเล็กมาและเป็นสีเทา มันเลยอ่านยากไปหน่อย

**Comment by Srikridsadaporn** [comment]
เห็นด้วยคะว่าควรเพิ่มขนาดของตัวอักษร ทั้งในส่วนของ Tab ด้วย ลอง Zoom ที่ 100% แล้วมันอ่านค่อนข้างยาก
ลองปรับดูก่อนสักหน้าก็ดีคะ  เลือกที่มีข้อมูลมากๆหน้าหนึ่ง (หน้าศูนย์เรียนรู้หน่วยงานต่างๆ) และดูข้อมูลน้อยหน่อยหน้าหนึ่ง...จะได้ดูว่าควรเลือกประมาณใด  หรือจะหาวิธีเพิ่มความคมชัดได้...

**Comment by Srikridsadaporn** [comment]
ขออนุญาต Close Issue นี้ไปใช้ #41

**Comment by Srikridsadaporn** [comment]
อย่าลืม...แก้ font กับ logo ***ทุกหน้า***ด้วยนะค่ะ
