### ISSUE TITLE
Back Office : ปรับแก้การเพิ่มข้อมูลศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#37]
ปรับแก้ตามภาพด้านล่างด้วยนะคะ
ขอบคุณคะ
![image](https://user-images.githubusercontent.com/31124544/29909294-746b19ea-8e4f-11e7-94bf-40b9dbba1423.png)

**Comment by wannarukb** [comment]
แก้เรียบร้อยแล้วค่ะ 
ขออนุญาต ปัดข้อมูลขึ้นเป็นแถวเดียวกันนะคะ 
<img width="1263" alt="screen shot 2017-08-31 at 19 46 46" src="https://user-images.githubusercontent.com/23309321/29923863-2595a912-8e85-11e7-861b-0360db990398.png">

**Comment by Srikridsadaporn** [comment]
อย่าลืม...แก้ font กับ logo ***ทุกหน้า***ด้วยนะค่ะ
