### ISSUE TITLE
ฺBack Office : ปรับแก้การเพิ่มข้อมูลศูนย์เรียนรู้หน่วยงานต่างๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#38]
ปรับแก้ตามภาพด้านล่างด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/29911463-248ceb84-8e58-11e7-857d-51b06cca6d99.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1263" alt="screen shot 2017-08-31 at 19 47 48" src="https://user-images.githubusercontent.com/23309321/29923911-4db14c12-8e85-11e7-8ea4-6fa2d9d7c385.png">

**Comment by Srikridsadaporn** [comment]
อย่าลืม...แก้ font กับ logo ***ทุกหน้า***ด้วยนะค่ะ

**Comment by wannarukb** [comment]
แก้หมดแล้วค่ะ สามารถ download project ออกมาได้เลยค่ะ

**Comment by Srikridsadaporn** [comment]
download project ได้อย่างไร..และที่ไหนค่ะ @wannarukb

**Comment by Srikridsadaporn** [comment]
download project ได้แล้วคะ  ขอบคุณค่ะ  แลดขอโทษใจร้อนไปหน่อย @wannarukb

**Comment by wannarukb** [comment]
ค่าาา ถ้าติดตรงไหนบอกได้เลยนะคะ

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
