### ISSUE TITLE
ฺBack office : ปรับแก้การเพิ่มข้อมูลศูนย์การศึกษาพัฒนา

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#39]
ปรับแก้การเพิ่มข้อมูลศูนย์การศึกษาพัฒนา ตามภาพด้านล่างนะคะ

![image](https://user-images.githubusercontent.com/31124544/29915334-c56b8e86-8e65-11e7-8c88-84fdaa0c82e5.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1279" alt="screen shot 2017-08-31 at 19 49 34" src="https://user-images.githubusercontent.com/23309321/29923982-8d8dfbc8-8e85-11e7-9fd9-cee1e36d4795.png">

**Comment by RDPB2-Kuer** [comment]
ต้องแก้ font กับ logo ด้วยนะค่ะ

**Comment by Srikridsadaporn** [comment]
ขอปิดนะคะ
