### ISSUE TITLE
เพิ่มข้อมูลที่จัดเก็บในศูนย์เรียนรู้เศรษฐกิจพอเพียง

### ISSUE THREAD

**Issue by cmmadnat** [wannarukb/RDPB-System#4]
เพิ่ม G-Chat (String) กับ Line ID

**Comment by RDPB2-Kuer** [comment]
การจัดเก็บข้อมูลศูนย์เรียนรู้เศรษฐกิจพอเพียง ที่ปรับปรุงใหม่ (รอ กปร. ยืนยัน)
![image](https://user-images.githubusercontent.com/30930235/29406957-e572df44-836c-11e7-9f1c-c43be74135db.png)

**Comment by Srikridsadaporn** [comment]
กปร.ยืนยันแล้ว ขอให้ปรับแก้ตามรายละเอียดด้านบน ได้เลยค่ะ
