### ISSUE TITLE
รบกวนปรับ Icon ของ ศูนย์เรียนรู้เศรษฐกิจพอเพียง และสร้าง Icon ศูนย์ศึกษาการพัฒนาฯ 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#40]
รบกวนปรับ Icon ของ ศูนย์เรียนรู้เศรษฐกิจพอเพียง และสร้าง Icon ศูนย์ศึกษาการพัฒนาฯ ตามภาพด้านล่างด้วยนะคะ
ขอบคุณคะ

![image](https://user-images.githubusercontent.com/31124544/29954605-57287fee-8f03-11e7-9163-3bfb55f230b0.png)

**Comment by wannarukb** [comment]
แบบตามนี้ได้ไหมคะ
<img width="737" alt="screen shot 2017-09-04 at 02 10 19" src="https://user-images.githubusercontent.com/23309321/30005881-47015310-9116-11e7-8de2-1acca691e732.png">

<img width="453" alt="screen shot 2017-09-04 at 02 20 12" src="https://user-images.githubusercontent.com/23309321/30005937-9ee7f75e-9117-11e7-851a-54308d2b6d07.png">


ศูนย์เรียนรู้เศรษฐกิจพอเพียงค่ะ
<img width="296" alt="screen shot 2017-09-04 at 02 11 00" src="https://user-images.githubusercontent.com/23309321/30005886-571a8d48-9116-11e7-981e-335761d00a1d.png">

**Comment by Srikridsadaporn** [comment]
กปร.เลือกเรียบร้อยแล้ว...ขอบคุณค่ะ ขอปิด Issue นี้
