### ISSUE TITLE
Back office : ปรับการแสดงข้อมูลสถานะศูนย์เรียนรู้และสถานะข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#41]
1. รบกวนปรับหน้าจอทุกหน้าตามภาพด้านล่าง (แบบที่ 1 ฟอนต์คณิต)
![image](https://user-images.githubusercontent.com/31124544/30011493-e0a34b72-9161-11e7-9816-5f2f77a47cf6.png)
2. Logoศูนย์ศึกษาการพัฒนา ใช้ตามภาพด้านล่าง
![image](https://user-images.githubusercontent.com/31124544/30011649-309d66de-9163-11e7-8469-59b24da44496.png)
3  Logoศูนย์เรียนรู้เศรษฐกิจพอเพียงใช้ ตามภาพด้านล่าง
![image](https://user-images.githubusercontent.com/31124544/30011666-4d4b68f8-9163-11e7-89f8-1f7040d1a274.png)

ปล...อย่าลืมเปลี่ยน  Logo ที่ปรากฎในแต่ละหน้าจอด้วยนะคะ

**Comment by Srikridsadaporn** [comment]
รบกวนขอ Logo ของศูนย์เรียนรู้เศรษฐกิจพอเพียง และศูนย์ศึกษา ฯ  ที่เพิ่มเข้ามาเพื่อใช้กับ Mobile ด้วยนะคะ
ขอบคุณล่วงหน้าคะ
@wannarukb ขอก่อนนะคะ  จะได้ใช้ในการเขียน Mobile app ก่อน

**Comment by RDPB2-Kuer** [comment]
ขอให้ปรับ  Font ใหม่ทุกหน้าเลยนะค่ะ รบกวนเริ่มทยอยมาให้เลยค่ะ

**Comment by wannarukb** [comment]
ขอปรึกษาค่ะ ได้ปรับตัว icon ให้เรียบร้อยแล้ว แต่ icon ของศูนย์พัฒนา พอมันถูกย่อไปเล็กๆ อาจจะมองยาก เล็กเลยจะปรับเป็นแบบนี้ พอจะโอเคไหมคะ

<img width="77" alt="screen shot 2017-09-06 at 14 18 48" src="https://user-images.githubusercontent.com/23309321/30098979-58c1381e-930e-11e7-8f40-05fc9eca1fa6.png">

**Comment by RDPB2-Kuer** [comment]
OK ค่ะ

**Comment by RDPB2-Kuer** [comment]
รบกวนปรับ font มาให้ดูหน้าหนึ่งก่อนนะค่ะ

**Comment by wannarukb** [comment]
แบบนี้ค่ะ
<img width="1280" alt="screen shot 2017-09-07 at 08 59 13" src="https://user-images.githubusercontent.com/23309321/30142427-e882a888-93aa-11e7-9afb-867af62acbfc.png">

**Comment by Srikridsadaporn** [comment]
OK คะใช้ตามนี้ รบกวนดำเนินการกับหน้าอื่นๆ ต่อได้เลยค่ะ น้องเล็ก @wannarukb 
แล้วทะยอยส่งเรื่อยๆนะคะเพราะต้องใช้ใส่ในรายงานภายในไม่เกิน 15 กันยายนนี้
ขอบคุณมากคะ

**Comment by Srikridsadaporn** [comment]
น้องเล็กคะ  พี่รบกวนขอภายในวันจันทร์ที่ 11 กันยายน 2560 นะคะ เพราะจะต้องจัดทำเล่มอีก
คงจะปรับไปบ้างแล้วนะคะ...ขอบคุณล่วงหน้า และขอโทษด้วยนะคะ ที่ร่นเวลาลง  ถ้าส่วนไหนเสร็จแล้วระบกวนทะยอยส่งได้เลยนะคะ @wannarukb

**Comment by Srikridsadaporn** [comment]
อย่าลืม...แก้ font กับ logo ***ทุกหน้า***ด้วยนะค่ะ

**Comment by Srikridsadaporn** [comment]
น้องเล็กคะ
รบกวนปรับอีกหน่อยนะคะ คือ
1. ไม่ใช่ BOLD Font
2. เปลี่ยนสี TAB HEADER ให้สีอ่อนลงนะคะ
3. สถานะข้อมูลให้เลือก ไฮไลท์ ที่ "ไม่ครบถ้วน" โดยใช้สีเหลืองที่ใช้กับพื้นที่เป้าหมาย 
![image](https://user-images.githubusercontent.com/31124544/30269659-ce4e3e16-9713-11e7-9c96-85efd15d2da4.png)
4.สถานะศูนย์เรียนรู้ ให้เลือก ไฮไลท์ ที่ "พื้นที่เป้าหมาย" โดยใช้สีเดิมที่ไฮไลท์ศูนย์เรียนรู้ (ฟ้าอมเขียว)
![image](https://user-images.githubusercontent.com/31124544/30269619-a4cda446-9713-11e7-8224-afe870d65aa5.png)


ขอบคุณล่วงหน้าคะ  @wannarukb

**Comment by wannarukb** [comment]
ข้อ 1, 3, 4เล็กปรับให้หมดแล้วนะคะ สีแบบนี้ถูกต้องไหมคะ 

<img width="1029" alt="screen shot 2017-09-12 at 22 05 55" src="https://user-images.githubusercontent.com/23309321/30333592-77d8bf1c-9807-11e7-930e-c6af28c520cf.png">


ส่วน Tab header เป็นสีนี้ได้ไหมคะ
<img width="1278" alt="screen shot 2017-09-12 at 22 11 53" src="https://user-images.githubusercontent.com/23309321/30333678-b3a1ed84-9807-11e7-923c-797a76174acd.png">

**Comment by Srikridsadaporn** [comment]
น้องเล็กคะ @wannarukb 
ขอเพิ่มรายละเอียดนะคะ เพราะที่ปรับมาถูกครึ่งหนึ่งแล้ว 
 แต่ขอโทษที่พี่ไม่ได้บอกรายละเอียดส่วนด้านล่างให้ด้วย
1. สถานะศูนย์เรียนรู้   ที่เป็น ศูนย์เรียนรู้ใช้ตัวอักษรเป็นปกติเลยคะ จะไฮไลท์เฉพาะ "พื้นที่เป้าหมาย"
2. สถานะข้อมูล   จะไฮไลท์เฉพาะ "ไม่ครบถ้วน" ส่วนที่ "ครบถ้วน" ใช้อักษรปกติเลยค่ะ
***ปรับทุกหน้าที่มีการแสดง สถานะศูนย์เรียนรู้ และสถานะข้อมูลนะคะ***
3.ส่วน Tab header ที่ปรับใช้สีเดียวกันหมดพี่กื้อว่าอย่างไรคะ @RDPB2-Kuer 

![image](https://user-images.githubusercontent.com/31124544/30359706-b982e8ce-9876-11e7-8577-73eff6aeab49.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่าา
<img width="660" alt="screen shot 2017-09-15 at 16 44 47" src="https://user-images.githubusercontent.com/23309321/30476820-6541d458-9a35-11e7-8b5b-be8b14f1d913.png">

**Comment by Srikridsadaporn** [comment]
@wannarukb  น้องเล็กคะ 
สถานะของข้อมูล และสถานะศูนย์เรียนรู้ มีทั้งหมด 4 หน้า ซึ่งเป็นของ ศูนย์เรัยนรู้เศรษฐกิจพอเพียง ศูนย์เรียนรู้ตามแนวพระราชดำริ  ศูนย์เรียนรู้หน่วยงานต่างๆ และศูนย์ศึกษาการพัฒนา 
น้องได้เปลี่ยนทั้งหมดแล้วหรือไม่คะ
ถ้าเปลี่ยนหมดแล้วพี่รบกวนขอเลยคะ..จะได้ปรับรายงานวันนี้  ไม่อย่างนั้นจะทำไม่ทันคะ
ขอบคุณมากคะ

**Comment by wannarukb** [comment]
ปรับให้เรียบร้อยแล้วค่ะ เล็กอัพขึ้น Project  ให้เรียบร้อยแล้วค่ะ

**Comment by wannarukb** [comment]
<img width="1033" alt="screen shot 2017-09-16 at 11 26 13" src="https://user-images.githubusercontent.com/23309321/30509097-e0ecf942-9ad1-11e7-8446-34223ef7a13f.png">
<img width="1017" alt="screen shot 2017-09-16 at 11 26 06" src="https://user-images.githubusercontent.com/23309321/30509098-e0f02036-9ad1-11e7-884c-88c4230355ca.png">
<img width="1018" alt="screen shot 2017-09-16 at 11 26 01" src="https://user-images.githubusercontent.com/23309321/30509099-e0f255a4-9ad1-11e7-8954-2bfb2b24ff92.png">
<img width="1021" alt="screen shot 2017-09-16 at 11 25 55" src="https://user-images.githubusercontent.com/23309321/30509100-e0f41dda-9ad1-11e7-9939-d5bdae03f967.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณมากคะ
