### ISSUE TITLE
Map : ปรับปรุงการแสดงเงื่อนไขบนแผนที่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [wannarukb/RDPB-System#42]
หน้าจอที่เคยน้องเล็กเคยออกแบบไว้ คือ
![image](https://user-images.githubusercontent.com/30930235/30055159-bd81f704-9258-11e7-9612-6573e38715ae.png)

จะขอปรับแก้ 3 จุด คือ
1. ส่วนที่เป็นเงื่อนไขการค้นหาด้านบน ขอให้ปรับปรุงใหม่ตามแบบนี้ คือ
![picture1](https://user-images.githubusercontent.com/30930235/30055283-29ae98ba-9259-11e7-9f43-f763e9a703ed.png)

2. เมื่อค้นหาแล้ว ข้อมูลที่ค้นหาอาจมีมากกว่า 1 รายการ ดังนั้น จึงกำหนดให้แสดงผลข้อมูลที่ค้นหา เป็น Box ด้านขวามือ ซึ่งจะแสดงรายการข้อมูลอย่างใดอย่างหนึ่ง คือ โครงการฯ หรือ ศูนย์เรียนรู้ ดังนี้
กรณี ค้นหาด้วยชื่อโครงการ :-
![image](https://user-images.githubusercontent.com/30930235/30055514-f16e238e-9259-11e7-98b9-9f912cbe69be.png)

กรณี ค้นหาด้วยชื่อศูนย์เรียนรู้ :-
![image](https://user-images.githubusercontent.com/30930235/30055570-113fbaf6-925a-11e7-87e0-f4a1fd29e150.png)

3. สำหรับด้านซ้ายมือที่เดิมมี Icon 6 อัน จะลดลงเหลือ 4 อัน ได้แก่
![image](https://user-images.githubusercontent.com/30930235/30055654-55fa3144-925a-11e7-869d-0abc229c2b8b.png)

**Comment by wannarukb** [comment]
กดรับ invitations ก่อนนะฮะ
https://github.com/wannarukb/RDPB-System/invitations

พอรับแล้วจะได้กด Label ได้ฮะะ

![group](https://user-images.githubusercontent.com/23309321/30192573-861423b6-9472-11e7-9a5d-f33b0b726cbe.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

![map001](https://user-images.githubusercontent.com/23309321/30247186-68e8809e-9638-11e7-8dfe-eed23267a211.png)

**Comment by Srikridsadaporn** [comment]
รบกวนปรับตามภาพด้านล่างด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/30305362-aadf0756-979c-11e7-9a96-821c8495a430.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="748" alt="screen shot 2017-09-12 at 21 47 35" src="https://user-images.githubusercontent.com/23309321/30332235-0687d4f4-9804-11e7-82c1-cc507f1e0574.png">

**Comment by RDPB2-Kuer** [comment]
OK
