### ISSUE TITLE
Front Office : รบกวนปรับตามรายละเอียดด้านในด้วยนะคะ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#44]
รบกวนปรับตามภาพด้านล่างด้วยนะคะ
1. 
 ![image](https://user-images.githubusercontent.com/31124544/30304505-08302278-9798-11e7-9f46-e1a56546bcb3.png)

2. 
![image](https://user-images.githubusercontent.com/31124544/30304548-41557594-9798-11e7-840f-7d4b8960d71e.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ พอดีตอน generate มันไม่ติดไป ขอโทษค่ะ
![desktop hd copy 9](https://user-images.githubusercontent.com/23309321/30331534-48d46dba-9802-11e7-89b8-5fceb702479b.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณคะ
