### ISSUE TITLE
Back Office : ปรับ Logo ศูนย์ศึกษาฯ บนหน้าจอ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#45]
ต้องใช้ Logo 
![0005](https://user-images.githubusercontent.com/31124544/30366402-1994142c-9895-11e7-9955-98169dca86c6.png) นี้ไม่ใช่หรือค่ะ หรือมีเหตุผลอะไรที่ต้องเปลี่ยน..ถ้าใช่รบกวนบอกด้วยหน่อยนะคะ จะได้ชี้แจงกับลูกค้าได้  ถ้าจำผิดก็ช่วยแก้ด้วยนะคะและหน้าอื่นๆที่เป็นของศูนย์ศึกษาด้วย
ขอบคุณค่ะ

![image](https://user-images.githubusercontent.com/31124544/30366380-02e80cce-9895-11e7-8dd4-41d9ef8a4712.png)

**Comment by RDPB2-Kuer** [comment]
รบกวนช่วยเปลี่ยน Logo ให้ด้วยนะค่ะ พี่ต้องรีบทำเอกสารให้เสร็จนะค่ะ

**Comment by Srikridsadaporn** [comment]
รบกวนปรับดังนี้
1.เปลี่ยน LOGO  ศูนย์ศึกษาการพัฒนา ทุกหน้าด้วยนะคะ ใส่ตัวอย่างมาให้สองหน้าคะ
2.ไฮไลท์เฉพาะที่ข้อมูลไม่ครบ

![image](https://user-images.githubusercontent.com/31124544/30474361-a2eb6376-9a2d-11e7-9918-dcad29e368ed.png)

![image](https://user-images.githubusercontent.com/31124544/30474428-dbf35872-9a2d-11e7-9a9b-aaa1aa94ac24.png)

![image](https://user-images.githubusercontent.com/31124544/30474538-37732b3c-9a2e-11e7-82cb-041be8685763.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่าา
<img width="660" alt="screen shot 2017-09-15 at 16 44 47" src="https://user-images.githubusercontent.com/23309321/30476820-6541d458-9a35-11e7-8b5b-be8b14f1d913.png">

**Comment by Srikridsadaporn** [comment]
@wannarukb  น้องเล็กคะ 
1. ศูนย์ศึกษาการพัฒนามีทั้งหมด 5 นะคะที่ต้องเปลี่ยน Logo
2 . ส่วนสถานะของข้อมูล และสถานะศูนย์เรียนรู้ มีทั้งหมด 4 หน้า ซึ่งเป็นของ ศูนย์เรัยนรู้เศรษฐกิจพอเพียง ศูนย์เรียนรู้ตามแนวพระราชดำริ  ศูนย์เรียนรู้หน่วยงานต่างๆ และศูนย์ศึกษาการพัฒนา
 น้องได้เปลี่ยนทั้งหมดแล้วหรือไม่คะ
ถ้าเปลี่ยนหมดแล้วพี่รบกวนขอเลยคะ..จะได้ปรับรายงานวันนี้  ไม่อย่างนั้นจะทำไม่ทันคะ
ขอบคุณมากคะ

**Comment by wannarukb** [comment]
ศูนย์ศึกษาการพัฒนามีทั้งหมด 5 นะคะที่ต้องเปลี่ยน Logo 
ข้อนี้แอบงงนิดหน่อยค่ะ รบกวนอธิบายเพิ่มเติมได้ไหมคะ 
ขอบคุณค่ะ

**Comment by Srikridsadaporn** [comment]
หมวยถึง
1. logo ที่ Panel Menu
2. หน้าเพิ่มข้อมูล(ส่วนหลัก 1 หน้า) และส่วนย่อย3 หน้า (ที่เชื่อมโยงกับส่วนหลัก) คือ หน้าข้อมูลทั่วไป  หน้ารูปภาพประกอบ และหน้าเอกสารประกอบ
ไม่ทราบว่าจะทำให้เข้าใจหรืองงเพิ่ม พอดีวันนี้  net พี่มีปัญหาส่งรูปไม่ได้
แต่จริงๆคือหน้าของศูนย์ศึกษาทุุกหน้าที่มี LOgo คะ
ถ้าพี่อธิบายยังไม่เคลียร์บอกมานะคะ  จะหาทางส่งรูป

สรุปคือ"หน้าที่ต้องเปลี่ยน Logo คือหน้า Panel menu  หน้าเพิ่มข้อมูล(หลัก) และหน้าย่อย (1. หน้าข้อมูลทั่วไป 2.หน้ารูปภาพประกอบ และ 3.หน้าเอกสารประกอบ) ค่ะ

**Comment by Srikridsadaporn** [comment]
ขอบคุณมากคะ น้องเล็ก

**Comment by wannarukb** [comment]
สรุปคือครบแล้วใช่ไหมคะ >__<

**Comment by Srikridsadaporn** [comment]
ใช่ค่ะ... ขอบคุณน้องเล็กมาก
