### ISSUE TITLE
Web: BackOffice ปรับปรุงหน้าจอบันทึกศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#49]
@Wannarukb รบกวนปรับแก้ตามรายละเอียดในภาพ
1.
![image](https://user-images.githubusercontent.com/31124544/30905489-27063648-a39f-11e7-8a96-8b761f2b0dc9.png)
2.
![image](https://user-images.githubusercontent.com/31124544/30905532-4966c680-a39f-11e7-97e0-85ed69bd7b03.png)

**Comment by wannarukb** [comment]
ตรงเปลี่ยนไอคอน จะให้ใช้ไอคอนที่ซ้ำกันหรอคะ ? เพราะอันนี้จะมีคำว่า ศูนย์ศึกษา ฯ

**Comment by Srikridsadaporn** [comment]
ใช่คะ

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
