### ISSUE TITLE
เพิ่มข้อมูลศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by cmmadnat** [wannarukb/RDPB-System#5]
เพิ่มช่องให้สามารถใส่ "ศูนย์ศึกษาการพัฒนา/พื้นที่" (Textarea)

**Comment by RDPB2-Kuer** [comment]
พี่คิดว่าน่าจะมี field นี้ให้บันทึกข้อมูลแล้ว เพียงแต่เวลาแสดงตัวเลือก จะไม่ใช่ ชื่อ ที่เตรียมไว้ให้ แต่ต้องไปดึงข้อมูลจาก ศูนย์ศึกษาการพัฒนา ซึ่งน่าจะเป็นเรื่องของการ code มากกว่า

**Comment by RDPB2-Kuer** [comment]
การปรับแก้หน้าจอศูนย์เรียนรู้ตามแนวพระราชดำริฯ ที่ปรับปรุงใหม่ (รอ กปร. ยืนยัน)

![image](https://user-images.githubusercontent.com/30930235/29407191-d01b0256-836d-11e7-8f40-675a1c78f1aa.png)

**Comment by Srikridsadaporn** [comment]
กปร.ยืนยันแล้ว ขอให้ปรับแก้ตามรายละเอียดได้เลยค่ะ
