### ISSUE TITLE
ขอ Icon และรบกวนปรับขนาด

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#52]
น้องเล็กคะ
พี่รบกวนดำเนินการ
1. ปรับขนาด Icon ตามภาพด้านล่างให้มีขนาดเท่ากับ Icon อื่นๆ ด้วยนะคะ
 ![0005](https://user-images.githubusercontent.com/31124544/30944231-a5116734-a420-11e7-9f68-6f2281fe22f9.png)

2.ขอ Icon 
2.1 ![image](https://user-images.githubusercontent.com/31124544/30944360-738b49ae-a421-11e7-94aa-7467e51fba0b.png) 
2.2 ![image](https://user-images.githubusercontent.com/31124544/30944494-82de8834-a422-11e7-925b-70b9c648646e.png)
นี้ด้วย  พี่หาไม่เจอ  ภาพตัวอย่างพี่ตัดจากที่น้องเล็กใช้ในหน้าจอ Mobile ที่ออกแบบ 
และถ้าพี่ต้องการเพิ่มเติมจะแจ้งมาอีกนะคะ

หรือถ้าน้องเล็กมีไฟล์รวมตั้งแต่ต้นจนเสร็จก็ขอเป็นไฟล์ก็ได้นะคะ
ขอบคุณมากคะ
@wannarukb

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะะ >_<
ขอโทษที่ช้านะคะ

[icon submit.zip](https://github.com/wannarukb/RDPB-System/files/1369029/icon.submit.zip)

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
