### ISSUE TITLE
Web: Back Office ปรับ Icon แก้หน้า Dashboard 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#53]
น้องเล็กคะ 
@wannarukb   รบกวนปรับแก้หน้า Dashboard ตามภาพด้านล่างด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/31272043-c724b9cc-aab3-11e7-97b2-94137bc30834.png)

ขอบคุณมากคะ

**Comment by wannarukb** [comment]
อันนี้ก็เหมือนกันค่ะ logo ส่วนนี้จะให้ใช้แบบมีคำว่าศูนย์ศึกษา ฯ ถูกไหมคะ ?

**Comment by Srikridsadaporn** [comment]
ใช่คะ

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
