### ISSUE TITLE
ICON : ขอปรับ icon ศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#54]
น้องเล็กคะ  รบกวนดำเนินการด้วยนะคะ...ลูกค้าขอปรับคะ
ขอบคุณคะ
@wannarukb 

![image](https://user-images.githubusercontent.com/31124544/31646737-d9ccdce4-b32d-11e7-8a87-ecd457573c8f.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
[RDPB-logo ศูนย์เรียนรู้.zip](https://github.com/wannarukb/RDPB-System/files/1391933/RDPB-logo.zip)

**Comment by Srikridsadaporn** [comment]
ขอบคุณมากนะคะ

น้องเล็ก
