### ISSUE TITLE
ICON : ออกแบบศูนย์ศึกษาการพัฒนาเพิ่มค่ะ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#55]
น้องเล็กคะ 
รบกวนออกแบบศูนย์ศึกษาการพัฒนาเพิ่ม รายละเอียดดังนี้

![image](https://user-images.githubusercontent.com/31124544/31646829-85a6b44a-b32e-11e7-9406-c3845c96d3cf.png)

ขอบคุณมากนะคะ

ต้องรบกวนด้วยคะ  ลูกค้าขอมา

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ แบบนี้ได้ไหมคะ

![002](https://user-images.githubusercontent.com/23309321/31680697-46fee584-b39f-11e7-961e-a0d20fff824d.png)

**Comment by Srikridsadaporn** [comment]
คิดว่าได้นะคะ  แต่ขอส่งลูกค้าดูก่อน

ขอบคุณมากนะคะ  น้องเล็ก

**Comment by Srikridsadaporn** [comment]
@wannarukb 
น้องเล็กคะ

รบกวนปรับอีกตามรายละเอียดในภาพด้านล่างอีกนิดนะคะ....ขอบคุณคะ

![image](https://user-images.githubusercontent.com/31124544/31700368-0ab72d94-b3f3-11e7-990c-98ed09192a1c.png)

**Comment by wannarukb** [comment]
แก้แล้วค่ะ มีสองแบบนะคะ

แบบที่ 1
![003](https://user-images.githubusercontent.com/23309321/31781481-ba89cada-b522-11e7-9b1c-378d23574810.png)

แบบที่ 2
![004](https://user-images.githubusercontent.com/23309321/31781479-ba4d1c16-b522-11e7-8b05-d9408c0f57b0.png)

**Comment by Srikridsadaporn** [comment]
ขอบคุณมากนะคะ...น้องเล็ก
