### ISSUE TITLE
 Web App : ข้อมูลการปรับปรุงBack Office

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#56]
@wannarukb  น้องเล็กคะ
รบกวนดำเนินการดังนี้คะ

![image](https://user-images.githubusercontent.com/31124544/32029521-4be41dc2-ba1f-11e7-86bd-bc6cd980cfb8.png)
ถ้าไม่เข้าใจข้อมูลนี้ ก็ดู Issue ต่อไปนะคะ เพราะส่วนนี้คือการสรุปคะ
หญิง

@cmmadnat

**Comment by wannarukb** [comment]
ใส่ส่วนของ Backoffice เล็กแก้เรียบร้อยแล้วค่ะ ขอโทษที่ช้านะคะ

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
