### ISSUE TITLE
Web: Back Office ปรับปรุงหน้า Dashboard

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#57]
น้องเล็กคะ  @wannarukb 
รบกวนปรับรายละเอียดตามภาพด้วยนะคะ
ขอบคุณคะ

![image](https://user-images.githubusercontent.com/31124544/32029572-b343e182-ba1f-11e7-87e2-74aeab122337.png)
@cmmadnat

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ ขอโทษที่ช้าค่ะ
<img width="1264" alt="screen shot 2017-11-13 at 02 01 28" src="https://user-images.githubusercontent.com/23309321/32702250-9dca79c4-c816-11e7-857b-ce6fd6dc1565.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
