### ISSUE TITLE
Web : Back Office ปรับปรุงศูนย์เรียนรู้เศษฐกิจพอเพียง 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#58]
น้องเล็กคะ @wannarukb 
รบกวนปรับศูนย์เรียนรู้เศษฐกิจพอเพียง ตามรายละเอียดในภาพด้านล่างด้วยนะคะ
ขอบคุณคะ
1
![image](https://user-images.githubusercontent.com/31124544/32029997-26f8d400-ba22-11e7-8af8-62263cae0c54.png)
2
![image](https://user-images.githubusercontent.com/31124544/32030030-68f64b1c-ba22-11e7-921e-8c0a17762afb.png)
@cmmadnat

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1279" alt="screen shot 2017-11-13 at 02 21 23" src="https://user-images.githubusercontent.com/23309321/32702410-642198da-c819-11e7-8cad-0525ae6510c2.png">

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
