### ISSUE TITLE
Web: Back Office รบกวนปรับศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#59]
น้องเล็กคะ
รบกวนปรับศูนย์เรียนรู้ตามแนวพระราชดำริ  รายละเอียดตามภาพนะคะ
ขอบคุณคะ

![image](https://user-images.githubusercontent.com/31124544/32030072-c5d640b2-ba22-11e7-934d-450737fa8c46.png)
@cmmadnat

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1278" alt="screen shot 2017-11-13 at 02 17 51" src="https://user-images.githubusercontent.com/23309321/32702370-e27d30d2-c818-11e7-8fc6-7b575925dda3.png">

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
