### ISSUE TITLE
เพิ่มข้อมูลในศูนย์เรียนรู้หน่วยงานต่างๆ

### ISSUE THREAD

**Issue by cmmadnat** [wannarukb/RDPB-System#6]
เพิ่ม Tab ของข้อมูลการติดต่อ มีอย่างน้อยดังนี้

1. ผู้รับผิดชอบศูนย์เรียนรู้
2. เลขบัตรประชาชน*
3. เบอร์โทรศัพท์/โทรสาร
4. อีเมลล์
5. G-Chat
6. Line ID

**Comment by RDPB2-Kuer** [comment]
การจัดเก็บข้อมูลศูนย์เรียนรู้หน่วยงานต่างๆ ที่ปรับแก้ (รอ กปร. ยืนยัน)

![image](https://user-images.githubusercontent.com/30930235/29407080-4f56cc22-836d-11e7-9005-085635d9400b.png)

**Comment by Srikridsadaporn** [comment]
กปร.ยืนยันแล้ว ขอให้ปรับแก้ตามรายละเอียดด้านบน 
ยกเว้น Icon ที่จะต้องใช้ตามที่ได้สรุปครั้งล่าสุด
