### ISSUE TITLE
Web: Back Office  บกวนปรับ "ศูนย์เรียนรู้หน่วยงานต่างๆ" 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#60]
น้องเล็กคะ @cmmadnat 
1.รบกวนเปลี่ยนชื่อ "ศูนย์เรียนรู้หน่วยงานต่างๆ" เป็น "ศูนย์เรียนรู้อื่นๆ" รายละเอียดตามภาพแรก
2. เพิ่มรหัสไปรษณีย์ตามรายละเอียดในภาพ 2 ด้วยนะคะ...ขอบคุณคะ
1
![image](https://user-images.githubusercontent.com/31124544/32030146-3bc5ffa6-ba23-11e7-96fc-ce61b4a36dc2.png)

2 
![image](https://user-images.githubusercontent.com/31124544/32030241-e35b5c84-ba23-11e7-8c36-50499d3ace21.png)
@cmmadnat

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่า
<img width="1263" alt="screen shot 2017-11-13 at 02 11 24" src="https://user-images.githubusercontent.com/23309321/32702328-fc65359a-c817-11e7-8799-127042b840c2.png">

**Comment by Srikridsadaporn** [comment]
รหัสไปรษณีย์ ไม่ได้เป็นฟิลด์บังคับ ดังนั้นไม่ต้องมี "*"

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
