### ISSUE TITLE
Web : Back Office รบกวนปรับศูนย์ศึกษาการพัฒนา ค่ะ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#61]
น้องเล็กคะ
รบกวนปรับศูนย์ศึกษาการพัฒนา  รายละเอียดดังภาพด้านล่างนะคะ
ขอบคุณคะ
@wannarukb 
![image](https://user-images.githubusercontent.com/31124544/32030312-4a4449c4-ba24-11e7-9d8c-cf315422d00a.png)

@cmmadnat

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ ขอโทษที่ช้านะคะ
<img width="1277" alt="screen shot 2017-11-13 at 02 07 57" src="https://user-images.githubusercontent.com/23309321/32702289-8263c5e0-c817-11e7-913d-c22baa2284c2.png">

**Comment by Srikridsadaporn** [comment]
รหัสไปรณีย์ไม่บังคับใส่ ดังนั้นไม่ต้องมี " *" ค่ะ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
