### ISSUE TITLE
Mapping : ขอ Icon ที่ใช้บนแผนที่

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#67]
@wannarukb น้องเล็กคะ พี่รบกวนขอ  Icon ที่ใช้บนแผนที่ ตามภาพด้วยนะคะ
ส่วนนี้ยังไม่เคยขอเลย ลืมค่ะว่าต้องใช้ -   ขอบคุณล่วงหน้าคะ

![image](https://user-images.githubusercontent.com/31124544/32641953-8cc0da7a-c603-11e7-98ce-c359a4833529.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ ขอโทษที่ช้าค่ะ
[icon.zip](https://github.com/wannarukb/RDPB-System/files/1464417/icon.zip)

**Comment by Srikridsadaporn** [comment]
ขอบคุณมากคะ น้องเล์ก
