### ISSUE TITLE
Front : ปรับหน้าแสดงข้อมูล ศ.เศรษฐกิจพอเพียง

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#69]
@wannarukb  น้องเล็กค่ะ ลูกค้าชมว่า "สวยน่าสนใจ" รบกวนปรับอีกนิดนะคะ ข้อมูลที่จะต้องแสดงขาดไปหน่อยนึง
ขอบคุณค่ะ
![image](https://user-images.githubusercontent.com/31124544/33699053-49270bae-db43-11e7-87dd-0cc4195a7899.png)
@cmmadnat

**Comment by RDPB2-Kuer** [comment]
รบกวนน้องเล็กช่วยออกแบบเพิ่มเติม เนื่องจากหน้าจอที่ออกแบบมาแสดงข้อมูลที่ยังขาดอยู่ เบื้องต้นจะขอให้ปรับแก้การแสดงข้อมูลด้านล่าง อย่างไรก็ตามถ้าน้องเล็กไม่เห็นด้วยก็สามารถปรับปรุงให้ดีขึ้นได้ค่ะ

1. หัวข้อ "รางวัล" อาจแสดงแทนผู้ประสานงาน เนื่องจากแสดงชื่อผู้ประสานงาน 2 แห่ง

2. เพิ่มปุ่ม 2 ปุ่ม ได้แก่ "แผนที่ตั้ง" และ "นำทางบนแผนที่" ซึ่งจะเป็นปุ่มที่แสดงหน้าหรือหลังข้อมูลที่อยู่ศูนย์เรียนรู้ ซึ่งอาจะแสดงต่อจากหัวข้อ "รางวัล"

3. เพื่อความชัดเจนจึงขอให้เพิ่มหัวข้อใหญ่ตรงกรอบด้านล่างว่า "ผู้ประสานงาน"

**Comment by wannarukb** [comment]
แบบนี้ได้ไหมคะ 
โดยสีไอคอนและหัวข้อให้เป็นไปตาม​ศูนย์ต่างๆ และมีปุ่มให้กดอย่างชัดเจนเลย

![screencapture-file-users-wbill86-desktop-003-article-sufficient-economic-html-1512894394450](https://user-images.githubusercontent.com/23309321/33803270-90ae147c-ddbe-11e7-9835-bc87b9d807a7.png)

**Comment by Srikridsadaporn** [comment]
ข้อมูลครบ ถูกต้องค่ะ น้องเล็ก @wannarukb

**Comment by wannarukb** [comment]
ขออัพเดทเล็กแก้เป็นสีตามนี้นะคะ

![screencapture-file-users-wbill86-desktop-003-article-sufficient-economic-html-1512895406370](https://user-images.githubusercontent.com/23309321/33803365-e9f254c4-ddc0-11e7-834b-4240d34c0f1b.png)

**Comment by Srikridsadaporn** [comment]
คะ เยี่ยมเลยค่ะ สีใช้ตาม Icon  ที่น้องเล็กแก้สีถูกต้องค่ะ

ขอบคูณมากนะคะ

**Comment by RDPB2-Kuer** [comment]
OK
