### ISSUE TITLE
รบกวนออกแบบ Icon Mobile Application 

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#70]
น้องเล็กค่ะ รบกวนออกแบบ  Icon Mobile Application โดยใช้ชื่อว่า  "กปร. GIS" ซึ่งจะใช้แทนของเดิมตามภาพ 
ผอ.บอกว่าต้องการให้ดูดึงดูดมากกว่าเดิมซึ่งเป็นแค่สัญลักษณ์ของหน่วยงาน
@wannarukb 
![image](https://user-images.githubusercontent.com/31124544/33699563-81701656-db46-11e7-865b-866b33e9a8ba.png)

**Comment by RDPB2-Kuer** [comment]
กปร ขอให้มีข้อความใน icon ว่า กปร. GIS โดยมีสีที่ใช้เหมือนด้านล่างนี้ โดยไม่จำเป็นต้องมีสัญญลักษณ์ กปร
![89040](https://user-images.githubusercontent.com/30930235/33870543-dbf27eb8-df40-11e7-8317-d3316376228e.jpg)

**Comment by wannarukb** [comment]
แบบนี้ได้ไหมคะ มี 4 แบบ

แบบที่ 1
![001](https://user-images.githubusercontent.com/23309321/33902226-efed8032-dfa6-11e7-9d3f-f2cbaeb5ad05.png)

แบบที่ 2
![002](https://user-images.githubusercontent.com/23309321/33902244-f922e516-dfa6-11e7-94e8-97028832bb61.png)

แบบที่ 3
![003](https://user-images.githubusercontent.com/23309321/33902252-01c0ac3a-dfa7-11e7-83ad-8545b178eec2.png)

แบบที่ 4
![004](https://user-images.githubusercontent.com/23309321/33902260-07f7e78a-dfa7-11e7-8726-3a6c2cd8b929.png)

**Comment by Srikridsadaporn** [comment]
น้องเล็กคะ รบกวนปรับอีกนิด ตัดคำว่า "ROYAL DEVELOPMENT PROJECT" ออกทุกแบบนะคะ เพราะไม่ได้ใช้คำนี้

**Comment by RDPB2-Kuer** [comment]
รอ กปร ยืนยันก่อนนะคะ

**Comment by RDPB2-Kuer** [comment]
กปร เลือกแบบที่ 1 คะ
