### ISSUE TITLE
Front : ปรับหน้าแสดงข้อมูล ศ.อื่นๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#71]
น้องเล็กคะ รบกวนออกแบบ ตามรายละเอียดด้านล่าง แต่แบบอิงตาม IR#69 ด้วยนะคะ 

![image](https://user-images.githubusercontent.com/31124544/33758844-a056573c-dc32-11e7-8b1b-83f043ee22c0.png)

**Comment by wannarukb** [comment]
เป็นแบบนี้ได้ไหมคะ

![screencapture-file-users-wbill86-desktop-003-article-other-html-1512895969944](https://user-images.githubusercontent.com/23309321/33803420-3d96d536-ddc2-11e7-9ae8-b019c2fd02bb.png)

**Comment by Srikridsadaporn** [comment]
พี่ชอบนะ น้องเล็ก  แต่นำทางบนแผนที่ มี 2 พิกัดนะคะ  1.พิกัดที่ตั้งศูนย์ กับ 2. พิกัดอื่นๆที่เกี่ยวข้อง
 @RDPB2-Kuer พี่กื้อว่าอย่างไรคะ แบบนี้โอเคไหมคะ

**Comment by RDPB2-Kuer** [comment]
OK
