### ISSUE TITLE
Front : ปรับหน้าแสดงข้อมูล ศ.ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by Srikridsadaporn** [wannarukb/RDPB-System#72]
น้องเล็กคะ รบกวนออกแบบ ตามรายละเอียดด้านล่าง แต่แบบอิงตาม IR#69 ด้วยนะคะ

![image](https://user-images.githubusercontent.com/31124544/33759101-a9054130-dc33-11e7-96a2-c34967f5decc.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

![screencapture-file-users-wbill86-desktop-003-article-royal-html-1512896836510](https://user-images.githubusercontent.com/23309321/33803480-3bfdfb6c-ddc4-11e7-8dd8-1f20ebc2fc23.png)

**Comment by RDPB2-Kuer** [comment]
OK
