### ISSUE TITLE
ปรับแก้หน้าค้นหา ศูนย์เรียนรู้ตามแนวพระราชดำริ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [wannarukb/RDPB-System#8]
![image](https://user-images.githubusercontent.com/30930235/29219757-2bef27a4-7ee3-11e7-9a80-c45b81aeb06b.png)

**Comment by wannarukb** [comment]
ตรง ตัวกรองจะขอแก้เป็น
- จังหวัด
- ประเภท
- ศูนย์ศึกษาพัฒนา/พื้นที่
- สถานะศูนย์เรียนรู้

เป็นแบบนี้นะคะ จะได้ทำให้การค้นหาไปได้ทั้งแนวกว้างและแนวลึกเข้าไปได้อีกค่ะ 

ตัวอย่างการกรอง 
เลือก ประเภทเกษตรผสมผสาน , จังหวัดฉะเชิงเทรา, ศูนย์ศึกษาพัฒนา/พื้นที่ : ศูนย์เรียนรู้ , สถานะ : รอการอนุมัติ
หากต้องการค้นหาชื่อกลุ่ม/เกษตรกร สามารถใส่ตรง ช่องค้นหาได้เลย
